### ISSUE TITLE
issue using yaml anchors

### ISSUE THREAD

**Issue by Mariusthvdb** [elchininet/custom-sidebar#239]
Using a few repeating templates
```
  - item: ui-test
    match: data-panel
    order: 8
    icon_color: >
      [[[ @partial test
          return kleuren[deel] || 'var(--error-color)'; ]]]
    info: >
      [[[ @partial test
          return kleuren[deel] || 'var(--error-color)'; ]]]
    info_color: >
      [[[ @partial test
          return kleuren[deel] || 'var(--error-color)'; ]]]
```
to show as 

<img width="258" alt="Scherm­afbeelding 2024-11-28 om 15 54 59" src="https://github.com/user-attachments/assets/8279cea3-a717-4389-a8d6-cac650097ad1">

made me want to try to re-use those duplicates with anchors
```
  - item: ui-test
    match: data-panel
    order: 8
    icon_color: &color
      >
        [[[ @partial test
            return kleuren[deel] || 'var(--error-color)'; ]]]
    info: *color
    info_color: *color
```

in my other yaml config files this works just nicely, but using it in this plugin errors with

> Unhandled Promise Rejection: Error: custom-sidebar: Invalid configuration in ui-test, "info" property should be a string

I might have a typo (didnt think I do) but it breaks the complete [config](https://gist.github.com/Mariusthvdb/e41957dc6f66d9764e0480030c9bd386#file-sidebar-config-yaml-L202) which I edited so you can see what I do there in the partials for Test

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
If some `yaml` code is giving you issues, test it in the [js-yaml demo](https://nodeca.github.io/js-yaml/) (`yaml-js` is the library that `custom-sidebar` uses to parse the `yaml` configuration).

Without taking into account that you are trying to repeat the color variable in the `info` option. With your configuration, `info` and `info_color` will become objects instead of strings.

Try with this:

```yaml
- item: ui-test
  match: data-panel
  order: 8
  icon_color: &color >
    [[[ @partial test
      return kleuren[deel] || 'var(--error-color)'; ]]]
  info: *color
  info_color: *color
```

**Comment by Mariusthvdb** [comment]
nice tool!
and yes, that works.

but it's completely counter to what I've been using for years in all other yaml I have in home Assistant.
also the code editor doesnt understand that:

<img width="490" alt="Scherm­afbeelding 2024-11-28 om 21 50 27" src="https://github.com/user-attachments/assets/f4ed1948-bc44-4024-9dd5-a947f284445b">

check the incorrect coloring of the anchor.

odd this is working at all

**Comment by elchininet** [comment]
>but it's completely counter to what I've been using for years in all other yaml I have in home Assistant.

What you were doing works, it is not an error, but it doesn't like to `yaml-js`. You can open an issue or a discussion in the repo. Maybe there is an explanation for that.

**Comment by Mariusthvdb** [comment]
first I looked up a god example of what ive ben doing for years, and, importantly, what is according to the Yaml specifications:
```
  card-mod-view: &cam_background
    |
     vertical-layout {
       {% if is_state('input_boolean.weer_view_background','on') %}
       background: repeat url({{state_attr('camera.buienradar','entity_picture')}}) fixed;
       {% endif %}
     }
     hui-sections-view {
       {% if is_state('input_boolean.weer_view_background','on') %}
       background: repeat url({{state_attr('camera.buienradar','entity_picture')}}) fixed;
       {% endif %}
     }
  card-mod-subview: *cam_background
```

in card-mod theming. 
in the editor:
<img width="705" alt="Scherm­afbeelding 2024-11-29 om 10 01 59" src="https://github.com/user-attachments/assets/c462b916-9869-434d-8d2a-2d05f92031f8">

and fully functional for the views and subviews (which is the point of this mod here)

now in the YAML JavaScript parser tool

<img width="1329" alt="Scherm­afbeelding 2024-11-29 om 10 02 27" src="https://github.com/user-attachments/assets/f61b92e4-a825-4ac7-868a-395365a9bc84">

this is not recognized.

not sure what is causing this, but apparently there is not a full compliance with the yaml specifications

> What you were doing works,

well, that is just the thing, is works in any Yaml configured config, but Not in the custom-sidebar plugin.

> You can open an issue or a discussion in the repo. Maybe there is an explanation for that.

you mean in the https://github.com/nodeca/js-yaml repo? yes, I can do that, however, I see there is a lot of talk already on anchors not behaving as they are expected to... given the fact the resource hasn't been updated in 2 years, I dont think it will be of much use adding to that discussion dont you think? I see you were there a few hours ago, linking to https://github.com/yaml/yaml/issues/35 but the resource is from 

<img width="313" alt="Scherm­afbeelding 2024-11-29 om 10 09 51" src="https://github.com/user-attachments/assets/ea2f60b1-a071-431e-a5a1-247cb7b002bd">

**Comment by elchininet** [comment]
>first I looked up a god example of what ive ben doing for years, and, importantly, what is according to the Yaml specifications.

Keep doing it in Home Assistant, but do not do it for `custom-sidebar` because as we have checked, it will not work. Just move the folded/literal headers and it will work with `js-yaml`, even if it doesn't look good in the editor, I would chose what works over what it looks better.

>and in Inspector:

I think that is not related to what you wrote, I see it all the time.

>well, that is just the thing, is works in any Yaml configured config, but Not in the custom-sidebar plugin.

Not in `custom-sidebar` but in `js-yaml`, remember that `custom-sidebar` doesn't do any parsing of the `YAML`, `js-yaml` does. `js-yaml` is just a parser to convert YAML to `JSON` which is the markup that is supported natively by `JavaScript`, which is the language used for front-end plugins, but as it is mentioned in the documentation, there are multiple things from the `YAML` standard that will not work, just because it is just a parser. It will never do what a back-end language as Pyton does.

>you mean in the https://github.com/nodeca/js-yaml repo? yes, I can do that, however, I see there is a lot of talk already on anchors not behaving as they are expected to... given the fact the resource hasn't been updated in 2 years, I dont think it will be of much use adding to that discussion dont you think?

Well, it is the only solution if you want to discuss something, because the issue is coming from that library. From the `custom-sidebar` side there is nothing that can be done to solve something that is coming from the code of another library. 🙂

**Comment by Mariusthvdb** [comment]
understood, and I will adapt to be as understandable and readable as possible. Maybe because of that just keep he duplicates, I can not stand the sight in the editor, even knowing it works.....


as for the error, I do believe it comes from that, I only see it when using that yaml code, and no where else.... (did rather extensive testing and cleaning cache to find out)

> I see it all the time.

well you're using your own plugin too of course, maybe some exotic coding going on there ;-)

just kidding.
